# Generated by Django 2.1.4 on 2019-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
